Feed/Controllers/FeedController.cs
using Feed.Data;
using Feed.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace Feed.Controllers
{
    public class FeedController : Controller
    {
        private readonly FeedContext _context;

        public FeedController(FeedContext context)
        {
            _context = context;
        }

        // GET: Feed
        public async Task<IActionResult> Index()
        {
            return View(await _context.FeedModel.Include(x => x.Items).ToListAsync());
        }

        // GET: Feed/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var feedModel = await _context.FeedModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (feedModel == null)
            {
                return NotFound();
            }

            return View(feedModel);
        }

        // GET: Feed/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Feed/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title")] FeedModel feedModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(feedModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(feedModel);
        }

        // GET: Feed/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var feedModel = await _context.FeedModel.FindAsync(id);
            if (feedModel == null)
            {
                return NotFound();
            }
            return View(feedModel);
        }

        // POST: Feed/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title")] FeedModel feedModel)
        {
            if (id != feedModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(feedModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FeedModelExists(feedModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(feedModel);
        }

        // GET: Feed/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var feedModel = await _context.FeedModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (feedModel == null)
            {
                return NotFound();
            }

            return View(feedModel);
        }

        // POST: Feed/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var feedModel = await _context.FeedModel.FindAsync(id);
            _context.FeedModel.Remove(feedModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FeedModelExists(int id)
        {
            return _context.FeedModel.Any(e => e.Id == id);
        }
    }
}

Feed/Controllers/FeedItemController.cs
using Feed.Data;
using Feed.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace Feed.Controllers
{
    public class FeedItemController : Controller
    {
        private readonly FeedContext _context;

        public FeedItemController(FeedContext context)
        {
            _context = context;
        }

        // GET: FeedItem
        public async Task<IActionResult> Index(string searchString = "")
        {
            var items = from i in _context.FeedItemModel select i;

            if (!string.IsNullOrEmpty(searchString))
                items = items.Where(s => s.Title.Contains(searchString));

            return View(await items.ToListAsync());
        }

        // GET: FeedItem/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var feedItemModel = await _context.FeedItemModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (feedItemModel == null)
            {
                return NotFound();
            }

            return View(feedItemModel);
        }

        // GET: FeedItem/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: FeedItem/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Details")] FeedItemModel feedItemModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(feedItemModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(feedItemModel);
        }

        // GET: FeedItem/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var feedItemModel = await _context.FeedItemModel.FindAsync(id);
            if (feedItemModel == null)
            {
                return NotFound();
            }
            return View(feedItemModel);
        }

        // POST: FeedItem/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Details")] FeedItemModel feedItemModel)
        {
            if (id != feedItemModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(feedItemModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FeedItemModelExists(feedItemModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(feedItemModel);
        }

        // GET: FeedItem/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var feedItemModel = await _context.FeedItemModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (feedItemModel == null)
            {
                return NotFound();
            }

            return View(feedItemModel);
        }

        // POST: FeedItem/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var feedItemModel = await _context.FeedItemModel.FindAsync(id);
            _context.FeedItemModel.Remove(feedItemModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FeedItemModelExists(int id)
        {
            return _context.FeedItemModel.Any(e => e.Id == id);
        }
    }
}

Feed/Views/FeedItem/Create.cshtml
@model Feed.Models.FeedItemModel
@{
    ViewData["Title"] = "Create";
}

<h1>
    @ViewData["Title"] |
    <a asp-action="Index" asp-controller="Feed">Back to Feeds</a> |
    <a asp-action="Index">Back to Items</a>
</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Details" class="control-label"></label>
                <input asp-for="Details" class="form-control" />
                <span asp-validation-for="Details" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Feed/Views/FeedItem/Delete.cshtml
@model Feed.Models.FeedItemModel
@{
    ViewData["Title"] = "Delete";
}

<h1>
    @ViewData["Title"] |
    <a asp-action="Index" asp-controller="Feed">Back to Feeds</a> |
    <a asp-action="Index">Back to Items</a>
</h1>
<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Details)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Details)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
    </form>
</div>

Feed/Views/FeedItem/Details.cshtml
@model Feed.Models.FeedItemModel
@{
    ViewData["Title"] = "Details";
}

<h1>
    @ViewData["Title"] |
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index" asp-controller="Feed">Back to Feeds</a> |
    <a asp-action="Index">Back to Items</a>
</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Details)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Details)
        </dd>
    </dl>
</div>

Feed/Views/FeedItem/Edit.cshtml
@model Feed.Models.FeedItemModel
@{
    ViewData["Title"] = "Edit";
}

<h1>
    @ViewData["Title"] |
    <a asp-action="Index" asp-controller="Feed">Back to Feeds</a> |
    <a asp-action="Index">Back to Items</a>
</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Details" class="control-label"></label>
                <input asp-for="Details" class="form-control" />
                <span asp-validation-for="Details" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Feed/Views/FeedItem/Index.cshtml
@model IEnumerable<Feed.Models.FeedItemModel>
@{
    ViewData["Title"] = "Items";
}

<h1>
    <a asp-action="Index" asp-controller="Feed">Feeds</a> | @ViewData["Title"] |
    <a asp-action="Create">Create</a>
</h1>
<form asp-action="Index">
    <p>
        Title: <input type="text" name="SearchString">
        <input type="submit" value="Filter" class="btn btn-primary" />
    </p>
</form>
<table class="table">
    <tbody>
        @foreach (var item in Model.OrderBy(x => x.Title))
        {
            @await Html.PartialAsync("~/Views/FeedItem/_FeedItem.cshtml", item)
        }
    </tbody>
</table>

Feed/Views/FeedItem/_FeedItem.cshtml
@model Feed.Models.FeedItemModel

<tr>
    <td>
        --> @Html.DisplayFor(modelItem => Model.Title)
    </td>
    <td>
        @Html.DisplayFor(modelItem => Model.Details)
    </td>
    <td>
        <a asp-action="Edit" asp-controller="FeedItem" asp-route-id="@Model.Id">Edit</a> |
        <a asp-action="Delete" asp-controller="FeedItem" asp-route-id="@Model.Id">Delete</a>
    </td>
</tr>